# Generated by Django 3.2.3 on 2021-05-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210523_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shippingAddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
