# Generated by Django 3.2.3 on 2021-06-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
